%pulse amplitude modulation
clc;
clear all;
close all;
a=input("Enter Amplitude: ");
fc=input("Enter Corner Frequency: ");
fm=input("Enter Message Frequency: ");
fs=100*fc;
t=0:1/fs:4/fm;
x1=a*sin(2*pi*fm*t);
x2=0.5*square(2*pi*fc*t)+0.5;
y=x1.*x2;
subplot(3,1,1);
plot(t,x1,"RED");
xlabel("Time");
ylabel("Amplitude");
title("Msg/SUBRAT/074");
legend("Message");
grid on;
subplot(3,1,2);
plot(t,x2,"RED");
xlabel("Time");
ylabel("Amplitude");
title("Carrier/SUBRAT/074");
legend("Carrier");
grid on;
subplot(3,1,3);
plot(t,y,"RED");
xlabel("Time");
ylabel("Amplitude");
title("PAM/SUBRAT/074");
legend("PAM Signal");
grid on;
